//! Generated by `scripts/acp_catalog.py`; do not edit by hand.
//!
//! Lock name → `package-lock.json` of every npm release in the catalog.

/// Lockfiles embedded in the binary.
pub static LOCKS: &[(&str, &str)] = &[];
